version: '3'

services:
  mongo:
    image: bitnami/mongodb:7.0.5
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGODB_ROOT_PASSWORD: "pass"

  # mongo-express:
  #   image: library/mongo-express:1.0.2-20-alpine3.19
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: "pass"
  
